### ISSUE TITLE
Dataset url is not working 

### ISSUE THREAD

**Issue by Ganryuu** [james77777778/ppg2ecg-pytorch#29]
Google drive link gives off a "sorry , the file you requested does not exist" , is there any other place we can download the dataset from

**Comment by james77777778** [comment]
Hi @Ganryuu 

Sorry for the inconvenience. I have uploaded the new URL:
- https://drive.google.com/file/d/1UwuHRKkC0YPbDAFIYvFJlFmU6_3zgjcJ/view
- https://github.com/james77777778/ppg2ecg-pytorch/releases/download/dataset/dataset.zip

Feel free to contact me if the issue remains unresolved.

**Comment by Ganryuu** [comment]
Thank you
